# Generated by Django 4.2.17 on 2025-01-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='Pending', max_length=10)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
